import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import { z } from 'zod';
import { errorEnvelope } from '../response.js';
import { ERROR_CODES } from '../errors.js';
import type { AuthedRequest } from '../auth.js';

/**
 * Platform BFF routes. These are the dashboard's backend — session-gated,
 * NOT API-key-gated. For this scaffold we gate by a shared secret passed
 * in the `x-platform-session` header (generated by the platform app on
 * each request from the signed NextAuth JWT). Full session integration
 * lands when the platform shares its NextAuth JWKS with the gateway.
 */

export interface PlatformRouteDeps {
  readonly pool: Pool;
}

const UsageQuery = z.object({
  key_id: z.string().uuid().optional(),
  from: z.string().optional(),
  to: z.string().optional(),
  granularity: z.enum(['hour', 'day']).default('day'),
});

function requireSession(req: FastifyRequest): { userId: string } | null {
  // Scaffold-grade auth: require the platform shared secret + a user hint.
  const secret = req.headers['x-platform-secret'];
  const userId = req.headers['x-platform-user-id'];
  const configured = process.env['PLATFORM_SHARED_SECRET'];
  if (!configured) return null;
  if (typeof secret !== 'string' || secret !== configured) return null;
  if (typeof userId !== 'string' || userId.length === 0) return null;
  return { userId };
}

export async function registerPlatformRoutes(
  app: FastifyInstance,
  deps: PlatformRouteDeps,
): Promise<void> {
  app.get('/platform/usage', async (req, reply) => {
    const rid = (req as AuthedRequest).requestId ?? 'unknown';
    const session = requireSession(req);
    if (!session) {
      return reply
        .status(401)
        .send(errorEnvelope(ERROR_CODES.UNAUTHORIZED, 'platform session required', rid));
    }
    const parsed = UsageQuery.safeParse(req.query);
    if (!parsed.success) {
      return reply
        .status(400)
        .send(errorEnvelope(ERROR_CODES.BAD_REQUEST, 'invalid query', rid, parsed.error.flatten()));
    }

    const { key_id, from, to, granularity } = parsed.data;
    const truncExpr = granularity === 'hour' ? "date_trunc('hour', occurred_at)" : "date_trunc('day', occurred_at)";
    const cutoffFrom = from ?? new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
    const cutoffTo = to ?? new Date().toISOString();

    const params: unknown[] = [cutoffFrom, cutoffTo];
    let whereKey = '';
    if (key_id) {
      // Additional guard: key must belong to this user.
      params.push(key_id, session.userId);
      whereKey = `AND ue.key_id = $${params.length - 1}::uuid`;
      params.push(); // ensure param count alignment
    }

    const result = await deps.pool.query<{ bucket: Date; via: string; c: string }>(
      `SELECT ${truncExpr} AS bucket, COALESCE(via, 'api') AS via, COUNT(*) AS c
         FROM usage_events ue
        WHERE ue.occurred_at >= $1::timestamptz
          AND ue.occurred_at <= $2::timestamptz
          AND ue.key_id IN (SELECT id FROM api_keys WHERE user_id = '${session.userId}'::uuid)
          ${whereKey}
        GROUP BY bucket, via
        ORDER BY bucket ASC`,
      [cutoffFrom, cutoffTo],
    );
    return reply.send({ data: result.rows });
  });

  app.get('/platform/health/sources', async (_req, reply) => {
    // Returns a minimal snapshot — the full health check lives in
    // @bbs/orchestrator's checkOrchestratorHealth and is mounted at
    // /admin/health already. This endpoint lets the dashboard render the
    // per-source quota gauges without requiring the ADMIN_KEY.
    return reply.send({
      data: {
        sources: [],
        generated_at: new Date().toISOString(),
        note: 'Wire to checkOrchestratorHealth in a follow-up prompt.',
      },
    });
  });
}
